export const genres: Array<any> = [
  {
    id: 1,
    name: 'Todos',
  },
  {
    id: 2,
    name: 'Autoayuda',
  },
  {
    id: 3,
    name: 'Romance',
  },
  {
    id: 4,
    name: 'Fantasía',
  },
  {
    id: 5,
    name: 'Terror',
  },
];

export const books: Array<any> = [
  {
    author: 'Chinua Achebe',
    country: 'Nigeria',
    src: 'images/things-fall-apart.jpg',
    language: 'English',
    link: 'https://en.wikipedia.org/wiki/Things_Fall_Apart\n',
    pages: 209,
    title: 'Things Fall Apart',
    year: 1958,
    stars: 4,
    liked: true,
    genreId: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 1,
    lastBook: false,
  },
  {
    author: 'Hans Christian Andersen',
    country: 'Denmark',
    src: 'images/fairy-tales.jpg',
    language: 'Danish',
    link:
      'https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n',
    pages: 784,
    title: 'Fairy tales',
    year: 1836,
    stars: 3,
    liked: false,
    genreId: 3,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 2,
    lastBook: true,
  },
  {
    author: 'Dante Alighieri',
    country: 'Italy',
    src: 'images/the-divine-comedy.jpg',
    language: 'Italian',
    link: 'https://en.wikipedia.org/wiki/Divine_Comedy\n',
    pages: 928,
    title: 'The Divine Comedy',
    year: 1315,
    stars: 1,
    liked: false,
    genreId: 4,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 3,
    lastBook: true,
  },
  {
    author: 'Unknown',
    country: 'Sumer and Akkadian Empire',
    src: 'images/the-epic-of-gilgamesh.jpg',
    language: 'Akkadian',
    link: 'https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n',
    pages: 160,
    title: 'The Epic Of Gilgamesh',
    year: -170,
    stars: 2,
    liked: true,
    genreId: 5,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 4,
    lastBook: false,
  },
  {
    author: 'Unknown',
    country: 'Achaemenid Empire',
    src: 'images/the-book-of-job.jpg',
    language: 'Hebrew',
    link: 'https://en.wikipedia.org/wiki/Book_of_Job\n',
    pages: 176,
    title: 'The Book Of Job',
    year: -600,
    stars: 3,
    liked: true,
    genreId: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 5,
    lastBook: true,
  },
  {
    author: 'Unknown',
    country: 'India/Iran/Iraq/Egypt/Tajikistan',
    src: 'images/one-thousand-and-one-nights.jpg',
    language: 'Arabic',
    link: 'https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n',
    pages: 288,
    title: 'One Thousand and One Nights',
    year: 1200,
    stars: 3,
    liked: false,
    genreId: 3,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In semper, quam vel maximus eleifend, eros ex dignissim sapien, sit amet pretium nulla nisl sollicitudin risus. ',
    id: 6,
    lastBook: false,
  },
];
